site_name: zoeminus
repo_url: https://github.com/zoeplus/zoeminus
repo_name: zoeminus
edit_uri: 'commits/main/docs/'

nav:
  - 主页: 'index.md'
  - 一:
    - '集合论': 'Math/Set.md'
    - '实数理论': 'Math/R.md'
    - '一般拓扑学': 'Math/GTopo.md'
    - '实变函数': 'Math/RF.md'
    - '矩阵代数': 'Math/MAlg.md'
  - 九:
    - '概率论': 'Math/Prob.md'
    - '数理统计': 'Math/Stat.md'
    - '最优化理论': 'Math/Opt.md'
    - '数据结构与算法': 'Math/DSA.md'
    - '计算学习理论': 'Math/CLT.md'
  - 二十二:
    - '数据挖掘': 'Math/DM.md'
    - '统计学习': 'Math/SL.md'
    - '深度学习': 'Math/DL.md'
  - 二十: 
    - 'C': 'Coding/C.md'
    - 'C++': 'Coding/CPP.md'
    - 'Python': 'Coding/Python.md'
    - 'Sage': 'Math/Sage.md'
  - 十九:
    - 'PyTorch': 'Cookbooks/DLCB.md'
    - 'Python DM & ML': 'Cookbooks/PyDCB.md'
  - 零零五五:
    - '遥望': 'Parrot/Divisadero.md'
    - '感官刺激': 'Parrot/Senses.md'
    - '清醒的梦': 'Parrot/LucidDreaming.md'
    - '落': 'Parrot/Falling.md'
    - '对话': 'Parrot/WithLLM.md'
    - '存在主义': 
      - '存在 I': 'Parrot/Existential.md'
      - '对存在的追求': 'Parrot/B&N.md'

plugins:
  - search
  # - git-revision-date
  - git-revision-date-localized:
      locale: zh
      type: date
      timezone: Asia/Shanghai
      # fallback_to_build_date: false
      enable_creation_date: true
  - callouts # converting obsidian callouts
  - tags
  - roamlinks
        
# Extensions
markdown_extensions:
  - footnotes
  - meta
  - nl2br # callouts 
  - admonition # callouts
  - pymdownx.superfences # callouts
  - pymdownx.tabbed: # tabbed blocks
      alternate_style: true
  - pymdownx.details # callouts
  - attr_list # annotations
  - md_in_html # annotations
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''
  - toc:
      title: 本文组织：
      permalink: true
      baselevel: 2

theme:
  name: material
  language: zh
  locale: en
  favicon: imgs/zxr.ico
  logo: imgs/zx.png
  icon:
    annotation: material/alpha-z-circle
  features:
    - revision.date
    - navigation.path
    - navigation.top
    - navigation.footer
    # - toc.integrate 
    - content.action.edit
    # - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: 切暗色
    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/lightbulb
        name: 切亮色

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:2210377@mail.nankai.edu.cn
      name: Email
    - icon: fontawesome/brands/github
      link: https://github.com/zoeplus
      name: Github Profile

extra_javascript:
  # the following mathjax is not rendering normally
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/copy-tex.min.js
  - javascripts/katex.js    # katex
  - javascripts/tabSync.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - stylesheets/extra.css

copyright: Copyright &copy 2024 zoeminus
