name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: python -m pip install -r requirements.txt
      - run: |
          python -m mkdocs gh-deploy --force
